# Generated by Django 2.2.3 on 2019-07-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.PositiveIntegerField(default=675432123),
            preserve_default=False,
        ),
    ]
