# Generated by Django 2.2.3 on 2019-07-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='available_from',
            field=models.DateField(),
        ),
    ]
