# Generated by Django 2.2.3 on 2019-08-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0002_auto_20190812_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='vehicle_image',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
    ]
