# Generated by Django 2.2.3 on 2019-07-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0002_auto_20190730_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='availability',
            field=models.BooleanField(null=True),
        ),
    ]
