# Generated by Django 2.2.3 on 2019-07-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0002_auto_20190726_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='vehicle_type',
            field=models.CharField(choices=[('Car', 'Car'), ('Car', 'Motor')], max_length=100),
        ),
    ]
