# Generated by Django 2.2.3 on 2019-07-30 09:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adverts', '0003_auto_20190730_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='purchasers',
            field=models.ManyToManyField(related_name='purchasers', to=settings.AUTH_USER_MODEL),
        ),
    ]
