# Generated by Django 2.2.3 on 2019-08-12 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0003_auto_20190812_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advert',
            old_name='vehicle_image',
            new_name='image',
        ),
    ]
