# Generated by Django 2.2.3 on 2019-07-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0003_auto_20190726_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='vehicle_type',
            field=models.CharField(choices=[('Car', 'Car'), ('Motor', 'Motor'), ('Other', 'Other')], max_length=100),
        ),
    ]
