# Generated by Django 2.2.3 on 2019-07-26 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0004_auto_20190726_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='availability',
        ),
    ]
