# Generated by Django 2.2.3 on 2019-07-30 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0004_advert_purchasers'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='image',
            field=models.ImageField(blank=True, upload_to='vehicles_photos', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='available_from',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
