# Generated by Django 2.2.3 on 2019-08-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0005_auto_20190812_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos', verbose_name='Image'),
        ),
    ]
