# Generated by Django 2.2.3 on 2019-08-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0006_auto_20190812_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='available_from',
            field=models.DateField(),
        ),
    ]
