# Generated by Django 2.2.3 on 2019-07-29 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0007_auto_20190726_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='available_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='advert',
            name='price_per_day',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Price/day'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='vehicle_brand',
            field=models.CharField(max_length=100, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='vehicle_model',
            field=models.CharField(max_length=100, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='vehicle_type',
            field=models.CharField(choices=[('Car', 'Car'), ('Motor', 'Motor'), ('Other', 'Other')], max_length=100, verbose_name='Type'),
        ),
    ]
